name: MachineThatsDrawsGroupe3_CustomPCB
stepping:
  engine: RMT
  idle_ms: 255
  pulse_us: 4
  dir_delay_us: 0
  disable_delay_us: 50
axes:
  
  shared_stepper_disable_pin: gpio.6
  homing_runs: 1
  x:
    steps_per_mm: 80
    max_rate_mm_per_min: 5000
    acceleration_mm_per_sec2: 2000
    max_travel_mm: 170
    motor0:
      limit_all_pin: NO_PIN
      limit_neg_pin: gpio.0:low:pu 
      limit_pos_pin: NO_PIN    
      hard_limits: false
      pulloff_mm: 6
      standard_stepper:
        step_pin: gpio.4
        direction_pin: gpio.5
        disable_pin: NO_PIN
    homing:
      cycle: 1
      mpos_mm: 170          
      positive_direction: false  
      seek_mm_per_min: 600
      feed_mm_per_min: 200
      settle_ms: 500
  y:
    steps_per_mm: 42
    max_rate_mm_per_min: 5000
    acceleration_mm_per_sec2: 2000
    max_travel_mm: 140
    motor0:
      limit_all_pin: NO_PIN
      limit_neg_pin: gpio.19:low:pu
      limit_pos_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 6
      standard_stepper:
        step_pin: gpio.7
        direction_pin: gpio.8
        disable_pin: NO_PIN
    homing:
      cycle: 2
      mpos_mm: 140
      positive_direction: false
      seek_mm_per_min: 1000
      feed_mm_per_min: 200
      settle_ms: 250
  z:
    steps_per_mm: 100
    max_rate_mm_per_min: 5000
    acceleration_mm_per_sec2: 1000
    max_travel_mm: 5
    motor0:
      limit_all_pin: NO_PIN
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 1
      rc_servo:
        output_pin: gpio.17